# Generated by Django 4.1.12 on 2023-10-26 11:26

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('priority', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Task',
                'managed': True,
            },
        ),
    ]
